/** Human-readable renderings of a SessionRecord: post-call summary + transcript. */

import type { SessionRecord } from "./types.js";

function fmt(ms: number): string {
  const s = Math.floor(ms / 1000);
  return `${String(Math.floor(s / 60)).padStart(2, "0")}:${String(s % 60).padStart(2, "0")}`;
}

const STATUS_MARK: Record<string, string> = { covered: "✅", partial: "🟡", empty: "⬜️" };

/** MEDDPICC coverage summary with evidence and the questions surfaced. */
export function buildSummaryMarkdown(r: SessionRecord): string {
  const date = new Date(r.startedAt);
  const covered = r.slotDefs.filter((s) => r.slots[s.id as keyof typeof r.slots]?.status === "covered").length;
  const lines: string[] = [];

  lines.push(`# Discovery call — coverage summary`);
  lines.push("");
  lines.push(`- **When:** ${date.toLocaleString()}`);
  lines.push(`- **Duration:** ${fmt(r.durationMs)}`);
  lines.push(`- **Mode:** ${r.mode}${r.fixture ? ` (${r.fixture})` : ""}`);
  if (r.persona) lines.push(`- **Persona:** ${r.persona}`);
  lines.push(`- **Coverage:** ${covered} / ${r.slotDefs.length} slots covered`);
  const talkTotal = (r.talk?.repMs ?? 0) + (r.talk?.prospectMs ?? 0);
  if (talkTotal > 0) {
    const repPct = Math.round(((r.talk?.repMs ?? 0) / talkTotal) * 100);
    lines.push(`- **Talk ratio:** you ${repPct}% · prospect ${100 - repPct}%`);
  }
  lines.push("");

  if (r.notes && r.notes.trim()) {
    lines.push(`## Notes`);
    lines.push("");
    lines.push(r.notes.trim());
    lines.push("");
  }

  lines.push(`## MEDDPICC coverage`);
  lines.push("");
  lines.push(`| Slot | Status | Confidence | Evidence (verbatim prospect quote) |`);
  lines.push(`| --- | --- | --- | --- |`);
  for (const def of r.slotDefs) {
    const st = r.slots[def.id as keyof typeof r.slots];
    const mark = STATUS_MARK[st?.status ?? "empty"] ?? "";
    const conf = st?.confidence ? st.confidence.toFixed(2) : "—";
    const ev = st?.evidence?.[st.evidence.length - 1] ?? "";
    const evCell = ev ? `"${ev.replace(/\|/g, "\\|")}"` : "—";
    lines.push(`| ${def.label} | ${mark} ${st?.status ?? "empty"} | ${conf} | ${evCell} |`);
  }
  lines.push("");

  if (r.coaching) {
    lines.push(`## Coaching`);
    lines.push("");
    lines.push(`- Talk ratio (you): ${r.coaching.talkRatioRepPct}%`);
    lines.push(`- Questions asked: ${r.coaching.questionsAsked}`);
    lines.push(`- Your speaking pace: ${r.coaching.repWpm} wpm`);
    lines.push(`- Longest monologue: ${fmt(r.coaching.longestMonologueMs)}`);
    lines.push("");
  }

  if (r.perf) {
    lines.push(`## Real-time performance`);
    lines.push("");
    lines.push(`- Avg classifier latency: ${r.perf.avgClassifierMs} ms`);
    lines.push(`- Avg nudge latency: ${r.perf.avgNudgeMs} ms (${r.perf.speculativeHits} served instantly)`);
    if (r.perf.echoesSuppressed) lines.push(`- Rep-echo lines suppressed: ${r.perf.echoesSuppressed}`);
    lines.push("");
  }

  if (r.objections && r.objections.length) {
    lines.push(`## Objections raised (${r.objections.length})`);
    lines.push("");
    for (const o of r.objections) {
      lines.push(`- **[${fmt(o.ts)}] ${o.label}**${o.doc ? ` — battlecard: ${o.doc}` : ""}`);
    }
    lines.push("");
  }

  if (r.suggestions.length) {
    lines.push(`## Copilot nudges (${r.suggestions.length})`);
    lines.push("");
    for (const s of r.suggestions) {
      lines.push(`- **[${fmt(s.ts)}] ${s.slotId}** — ${s.question}`);
    }
    lines.push("");
  }

  const gaps = r.slotDefs.filter((s) => r.slots[s.id as keyof typeof r.slots]?.status !== "covered");
  if (gaps.length) {
    lines.push(`## Still open (follow up next call)`);
    lines.push("");
    for (const g of gaps) lines.push(`- ${g.label}`);
    lines.push("");
  }

  lines.push(`---`);
  lines.push(`_Generated by Converse — live sales qualification copilot._`);
  return lines.join("\n");
}

export function buildTranscriptMarkdown(r: SessionRecord): string {
  const lines = [`# Transcript — ${new Date(r.startedAt).toLocaleString()}`, ""];
  for (const t of r.transcript) {
    lines.push(`**[${fmt(t.tsStart)}] ${t.speaker === "rep" ? "You" : "Prospect"}:** ${t.text}`);
  }
  return lines.join("\n");
}
